import welileLogoUrl from '@/assets/welile-logo.png';
import { format } from 'date-fns';

const THEME_PRIMARY: [number, number, number] = [108, 33, 196];
const THEME_PRIMARY_DARK: [number, number, number] = [76, 22, 150];
const THEME_STRIPE: [number, number, number] = [243, 238, 252];
const THEME_ACCENT: [number, number, number] = [239, 176, 46];
const THEME_INK: [number, number, number] = [37, 31, 48];
const THEME_MUTED: [number, number, number] = [104, 96, 117];
const THEME_BORDER: [number, number, number] = [218, 208, 231];

export interface TenantCallReportRow {
  when: string;
  tenant: string;
  tenantPhone?: string | null;
  agent?: string | null;
  agentPhone?: string | null;
  status: string;
  category?: string | null;
  comment?: string | null;
  context?: string | null;
  officer?: string | null;
}

export interface TenantCallReportSummary {
  label: string;
  value: string;
}

export interface TenantCallReportMetadata {
  generatedBy: string;
  email: string;
  generatedAt: Date;
  reportPeriod: string;
}

/** Derived feedback analysis for the same period — see tenantCallFeedbackAnalysis. */
export interface TenantCallReportAnalysis {
  commented: number;
  totalCalls: number;
  insufficient: boolean;
  themes: { label: string; hint: string; count: number; pct: number; tone: string }[];
  categories: { label: string; count: number; pct: number }[];
  severities: { label: string; count: number }[];
  sentiment: { positive: number; negative: number; neutral: number };
  unresolved: { openAttempts: number; followUpsPending: number; disputesOpen: number; unreachable: number };
  recommendations: { title: string; detail: string }[];
}

async function loadLogoBase64(): Promise<string | null> {
  try {
    const res = await fetch(welileLogoUrl);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

/**
 * Branded Tenant Calls Report — same records as the Calling Hub spine, laid out
 * with the system's standard report header band, summary tiles and striped table.
 */
export async function generateTenantCallsReportPdf(
  periodLabel: string,
  summary: TenantCallReportSummary[],
  rows: TenantCallReportRow[],
  metadata: TenantCallReportMetadata,
  analysis?: TenantCallReportAnalysis,
): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf');
  const autoTableMod: any = await import('jspdf-autotable');
  const autoTable = autoTableMod.default || autoTableMod;

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 12;
  const logo = await loadLogoBase64();

  // ── Header band ──
  doc.setFillColor(...THEME_PRIMARY_DARK);
  doc.rect(0, 0, pageWidth, 31, 'F');
  doc.setFillColor(...THEME_PRIMARY);
  doc.rect(0, 0, 5, 31, 'F');
  doc.setFillColor(...THEME_ACCENT);
  doc.rect(0, 29, pageWidth, 2, 'F');
  if (logo) {
    try {
      doc.addImage(logo, 'PNG', margin, 6.5, 17, 17);
    } catch {
      /* ignore */
    }
  }
  const hx = logo ? margin + 21 : margin;
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Tenant Calls Report', hx, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Tenant Operations · Calling Center', hx, 19);
  doc.setFontSize(8);
  doc.text('CONFIDENTIAL OPERATIONAL REPORT', pageWidth - margin, 13, { align: 'right' });
  doc.text(`${rows.length.toLocaleString()} call record${rows.length === 1 ? '' : 's'}`, pageWidth - margin, 20, {
    align: 'right',
  });

  // ── Report metadata ──
  let y = 38;
  doc.setFillColor(249, 247, 252);
  doc.setDrawColor(...THEME_BORDER);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 25, 2, 2, 'FD');
  doc.setFillColor(...THEME_PRIMARY);
  doc.roundedRect(margin, y, 3, 25, 1.5, 1.5, 'F');

  const metadataItems = [
    ['Generated by', metadata.generatedBy],
    ['Email', metadata.email],
    ['Generated on', format(metadata.generatedAt, 'dd MMM yyyy, HH:mm:ss')],
    ['Report period', metadata.reportPeriod || periodLabel],
  ];
  const metaW = (pageWidth - margin * 2 - 12) / 4;
  metadataItems.forEach(([label, value], index) => {
    const x = margin + 7 + index * metaW;
    doc.setTextColor(...THEME_MUTED);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.text(label.toUpperCase(), x, y + 7);
    doc.setTextColor(...THEME_INK);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    const lines = doc.splitTextToSize(value, metaW - 5);
    doc.text(lines.slice(0, 2), x, y + 13);
  });

  // ── Summary tiles ──
  y += 32;
  const tileW = (pageWidth - margin * 2 - (summary.length - 1) * 3) / Math.max(summary.length, 1);
  summary.forEach((s, i) => {
    const x = margin + i * (tileW + 3);
    doc.setFillColor(...THEME_STRIPE);
    doc.setDrawColor(...THEME_BORDER);
    doc.roundedRect(x, y, tileW, 18, 2, 2, 'FD');
    doc.setFillColor(...THEME_PRIMARY);
    doc.roundedRect(x, y, tileW, 2, 1, 1, 'F');
    doc.setTextColor(...THEME_MUTED);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.text(s.label.toUpperCase(), x + 3, y + 7);
    doc.setTextColor(...THEME_PRIMARY_DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(s.value, x + 3, y + 15);
  });
  y += 27;

  // ── Feedback Analysis & Insights (derived from this period's comments only) ──
  if (analysis) {
    const pageH = doc.internal.pageSize.getHeight();
    doc.setTextColor(...THEME_PRIMARY_DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Feedback Analysis & Insights', margin, y);
    y += 2;
    doc.setDrawColor(...THEME_PRIMARY);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...THEME_MUTED);
    const intro = analysis.insufficient
      ? `Not enough officer comments in this period to read reliable patterns (${analysis.commented} comment(s) on ${analysis.totalCalls} call(s)). No conclusions are drawn.`
      : `Patterns counted from the ${analysis.commented} commented call(s) of ${analysis.totalCalls} in this period. Percentages are of commented calls. Original officer comments appear unchanged in the detailed table.`;
    const introLines = doc.splitTextToSize(intro, pageWidth - margin * 2);
    doc.text(introLines, margin, y);
    y += introLines.length * 4 + 2;

    if (!analysis.insufficient) {
      // Signal tiles
      const sig = [
        ['Comments analysed', String(analysis.commented)],
        ['Concern signals', String(analysis.sentiment.negative)],
        ['Positive signals', String(analysis.sentiment.positive)],
        ['Open attempts', String(analysis.unresolved.openAttempts)],
        ['Follow-ups pending', String(analysis.unresolved.followUpsPending)],
        ['Balance disputes', String(analysis.unresolved.disputesOpen)],
        ['Not reached', String(analysis.unresolved.unreachable)],
      ];
      const sw = (pageWidth - margin * 2 - (sig.length - 1) * 2.5) / sig.length;
      sig.forEach(([label, value], i) => {
        const x = margin + i * (sw + 2.5);
        doc.setFillColor(...THEME_STRIPE);
        doc.setDrawColor(...THEME_BORDER);
        doc.roundedRect(x, y, sw, 15, 2, 2, 'FD');
        doc.setTextColor(...THEME_MUTED);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.text(doc.splitTextToSize(label.toUpperCase(), sw - 4).slice(0, 1), x + 2.5, y + 5.5);
        doc.setTextColor(...THEME_PRIMARY_DARK);
        doc.setFontSize(11);
        doc.text(value, x + 2.5, y + 12.5);
      });
      y += 20;

      autoTable(doc, {
        head: [['Recurring theme', 'What it means', 'Calls', '% of commented']],
        body: analysis.themes.length
          ? analysis.themes.map((t) => [t.label, t.hint, String(t.count), `${t.pct}%`])
          : [['No recognisable pattern', 'Comments were recorded but matched no known theme.', '0', '0%']],
        startY: y,
        margin: { left: margin, right: margin },
        tableWidth: pageWidth - margin * 2,
        styles: {
          fontSize: 7.5,
          cellPadding: 1.8,
          overflow: 'linebreak',
          valign: 'top',
          textColor: THEME_INK,
          lineColor: THEME_BORDER,
          lineWidth: 0.15,
        },
        headStyles: { fillColor: THEME_PRIMARY, textColor: 255, fontSize: 7.5, fontStyle: 'bold', cellPadding: 2.2 },
        alternateRowStyles: { fillColor: THEME_STRIPE },
        columnStyles: {
          0: { cellWidth: 58, fontStyle: 'bold' },
          1: { cellWidth: 'auto' },
          2: { cellWidth: 16, halign: 'right' },
          3: { cellWidth: 28, halign: 'right' },
        },
      });
      y = ((doc as any).lastAutoTable?.finalY ?? y) + 6;

      if (analysis.categories.length) {
        autoTable(doc, {
          head: [['Feedback category tagged by officers', 'Calls', '% of tagged']],
          body: analysis.categories.map((c) => [c.label, String(c.count), `${c.pct}%`]),
          startY: y,
          margin: { left: margin, right: margin },
          tableWidth: (pageWidth - margin * 2) * 0.6,
          styles: {
            fontSize: 7.5,
            cellPadding: 1.8,
            textColor: THEME_INK,
            lineColor: THEME_BORDER,
            lineWidth: 0.15,
          },
          headStyles: { fillColor: THEME_PRIMARY_DARK, textColor: 255, fontSize: 7.5, fontStyle: 'bold', cellPadding: 2.2 },
          alternateRowStyles: { fillColor: THEME_STRIPE },
          columnStyles: { 1: { halign: 'right', cellWidth: 18 }, 2: { halign: 'right', cellWidth: 24 } },
        });
        y = ((doc as any).lastAutoTable?.finalY ?? y) + 6;
      }

      // Recommended officer actions
      if (y > pageH - 45) {
        doc.addPage();
        y = 20;
      }
      doc.setTextColor(...THEME_PRIMARY_DARK);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('Recommended Officer Actions / Areas for Attention', margin, y);
      y += 4;
      doc.setDrawColor(...THEME_ACCENT);
      doc.setLineWidth(0.6);
      doc.line(margin, y - 1.5, pageWidth - margin, y - 1.5);
      y += 1;

      if (analysis.recommendations.length) {
        analysis.recommendations.forEach((r, i) => {
          const detailLines = doc.splitTextToSize(`${i + 1}. ${r.title} — ${r.detail}`, pageWidth - margin * 2 - 4);
          if (y + detailLines.length * 3.6 > pageH - 16) {
            doc.addPage();
            y = 20;
          }
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(...THEME_INK);
          doc.text(detailLines, margin + 2, y + 4);
          y += detailLines.length * 3.8 + 2.5;
        });
      } else {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...THEME_MUTED);
        doc.text('The comments in this period do not point to any specific action.', margin + 2, y + 4);
        y += 8;
      }
      y += 4;
    }

    if (y > pageH - 60) {
      doc.addPage();
      y = 20;
    }
  }

  doc.setTextColor(...THEME_PRIMARY_DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Calls made in this period', margin, y);
  y += 2;
  doc.setDrawColor(...THEME_PRIMARY);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;

  autoTable(doc, {
    head: [['#', 'When', 'Tenant', 'Agent', 'Status', 'Feedback', 'Comment', 'Tenant plan', 'Officer']],
    body: rows.length
      ? rows.map((r, i) => [
          String(i + 1),
          r.when,
          r.tenantPhone ? `${r.tenant}\n${r.tenantPhone}` : r.tenant,
          r.agent ? (r.agentPhone ? `${r.agent}\n${r.agentPhone}` : r.agent) : '—',
          r.status,
          r.category || '—',
          r.comment || '—',
          r.context || '—',
          r.officer || '—',
        ])
      : [['', '', '', '', 'No calls recorded in this period', '', '', '', '']],
    startY: y,
    margin: { left: margin, right: margin },
    tableWidth: pageWidth - margin * 2,
    showHead: 'everyPage',
    styles: {
      fontSize: 7.5,
      cellPadding: 1.8,
      overflow: 'linebreak',
      valign: 'top',
      textColor: THEME_INK,
      lineColor: THEME_BORDER,
      lineWidth: 0.15,
    },
    headStyles: {
      fillColor: THEME_PRIMARY,
      textColor: 255,
      fontSize: 7.5,
      fontStyle: 'bold',
      cellPadding: 2.2,
    },
    alternateRowStyles: { fillColor: THEME_STRIPE },
    columnStyles: {
      0: { cellWidth: 8, halign: 'right' },
      1: { cellWidth: 26 },
      2: { cellWidth: 38 },
      3: { cellWidth: 34 },
      4: { cellWidth: 26 },
      5: { cellWidth: 30 },
      6: { cellWidth: 'auto' },
      7: { cellWidth: 40 },
      8: { cellWidth: 28 },
    },
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    const ph = doc.internal.pageSize.getHeight();
    doc.setFontSize(7.5);
    doc.setDrawColor(...THEME_BORDER);
    doc.line(margin, ph - 10, pageWidth - margin, ph - 10);
    doc.setTextColor(...THEME_MUTED);
    doc.text('Welile Tenant Operations · Confidential', margin, ph - 6);
    doc.text(`Page ${p} / ${pageCount}`, pageWidth - margin, ph - 6, { align: 'right' });
  }

  return doc.output('blob');
}
