// Fixed user-facing strings for every non-answer path. These are NEVER generated by the model,
// so a refusal cannot be talked out of itself.
// Terminology (CLAUDE.md): "Rent Plan", "Supporter", "Returns" — never loan / lender / ROI / interest.

export const MSG = {
  notAnAgent:
    "You don't seem to be an agent. This assistant is only available to agents who have tenants.",
  outOfScope:
    "I can only help with your own agent account: your collections, tenants, wallet and advances. " +
    "Try asking about one of those, or send this to the support team.",
  unmatched:
    "I couldn't match that to your account data. Could you rephrase it? " +
    "For example: “How much did I collect today?” or “What is my wallet balance?”",
  wantsHuman: "I can pass this conversation to the support team so they can follow up with you.",
  escalated: "Done. I've sent this conversation to the support team and they will follow up with you.",
  alreadyEscalated: "This conversation is already with the support team. They will follow up with you.",
  rateLimited: "You're sending messages very quickly. Please wait a minute and try again.",
  error: "I'm having trouble right now. Please try again in a moment.",
  invalidRequest: "That request wasn't valid.",
  unauthorized: "Please sign in again.",
} as const;

/** Outcomes after which we offer the "send to support" action. */
export const ESCALATION_OFFER_OUTCOMES = new Set(["out_of_scope", "unmatched", "blocked", "error"]);
