-- Aggregate click-performance reporting across every link-tracking system in
-- the platform, so "how many people interacted with a link we sent" has one
-- answer instead of four disconnected tables.
--
-- Four channels exist today, each tracking clicks differently:
--   * short_links / short_link_clicks   -- generic /r/:code shortener behind
--     auth invites, activation, funder-onboarding, landlord-signup, partner
--     registration, merchant registration, tenant registration, rent-plan
--     shares, house-support shares. click_count/last_clicked_at live on the
--     link row itself.
--   * recruitment_campaign_links / recruitment_campaign_clicks -- agent
--     recruitment "/join/{code}" links (the ones riding inside tenant
--     PAYMENT_FULL/PARTIAL SMS via get_tenant_status_appendices). Per-click
--     rows carry a converted_to_registration flag.
--   * career_link_clicks -- career-page landing hits keyed by UTM, no parent
--     link row (every visit is its own row).
--   * tenant_dashboard_links -- per-tenant, per-notification dashboard links
--     (use_count/last_used_at), tied back to tenant_notification_log via
--     notification_log_id.
--
-- NOTE: as of this migration, short_links click tracking was silently dead
-- for the /r/:code route (src/pages/ResolveRLink.tsx never called
-- record_short_link_click even though the RPC existed and TrackedRedirect.tsx
-- at /s/:code called it correctly) -- fixed in the same change that added
-- this function. Numbers for the short_link channel before 2026-09-21 undercount
-- real clicks for links generated by createShortLink.ts / useShortLink.ts.

create or replace function public.get_link_performance_summary(
  p_since timestamptz default now() - interval '30 days'
)
returns table (
  channel text,
  group_key text,
  links_created bigint,
  total_clicks bigint,
  links_with_clicks bigint,
  conversions bigint,
  last_click_at timestamptz
)
language plpgsql
stable
security definer
set search_path to 'public'
as $function$
begin
  if not exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and enabled = true
      and role in ('super_admin', 'manager', 'operations', 'coo', 'cfo', 'ceo', 'cto', 'cmo')
  ) then
    raise exception 'Only staff can view link performance';
  end if;

  return query
  with short_link_stats as (
    select
      'short_link'::text as channel,
      coalesce(sl.resource_type, sl.target_path, 'unknown') as group_key,
      count(*) as links_created,
      coalesce(sum(sl.click_count), 0)::bigint as total_clicks,
      count(*) filter (where sl.click_count > 0) as links_with_clicks,
      0::bigint as conversions,
      max(sl.last_clicked_at) as last_click_at
    from public.short_links sl
    where sl.created_at >= p_since
    group by coalesce(sl.resource_type, sl.target_path, 'unknown')
  ),
  recruitment_click_stats as (
    select
      'recruitment_campaign'::text as channel,
      coalesce(c.name, 'unknown') as group_key,
      count(distinct l.id) as links_created,
      count(*) filter (where cl.id is not null)::bigint as total_clicks,
      count(distinct cl.campaign_link_id) as links_with_clicks,
      count(*) filter (where cl.converted_to_registration)::bigint as conversions,
      max(cl.created_at) as last_click_at
    from public.recruitment_campaign_links l
    join public.recruitment_campaigns c on c.id = l.campaign_id
    left join public.recruitment_campaign_clicks cl
      on cl.campaign_link_id = l.id and cl.created_at >= p_since
    group by coalesce(c.name, 'unknown')
  ),
  career_click_stats as (
    select
      'career_page'::text as channel,
      coalesce(nullif(trim(cc.utm_campaign), ''), 'direct') as group_key,
      0::bigint as links_created,
      count(*)::bigint as total_clicks,
      0::bigint as links_with_clicks,
      0::bigint as conversions,
      max(cc.created_at) as last_click_at
    from public.career_link_clicks cc
    where cc.created_at >= p_since
    group by coalesce(nullif(trim(cc.utm_campaign), ''), 'direct')
  ),
  tenant_dashboard_stats as (
    select
      'tenant_dashboard'::text as channel,
      coalesce(tdl.purpose, 'unknown') as group_key,
      count(*) as links_created,
      coalesce(sum(tdl.use_count), 0)::bigint as total_clicks,
      count(*) filter (where tdl.use_count > 0) as links_with_clicks,
      0::bigint as conversions,
      max(tdl.last_used_at) as last_click_at
    from public.tenant_dashboard_links tdl
    where tdl.created_at >= p_since
    group by coalesce(tdl.purpose, 'unknown')
  )
  select * from short_link_stats
  union all
  select * from recruitment_click_stats
  union all
  select * from career_click_stats
  union all
  select * from tenant_dashboard_stats
  order by total_clicks desc;
end;
$function$;

grant execute on function public.get_link_performance_summary(timestamptz) to authenticated;
