import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "fs";
const db = new PGlite();
const CFO='29a0cfa8-1eaf-453c-874c-0fc72fa4f74b', CFO2='00000000-0000-4000-8000-0000000000c2', AGENT='dc5ba4af-cb53-4fe8-9aa5-b1b73d0402aa';
const q=async(s:string)=>{try{const r=await db.query(s);return r.rows}catch(e:any){return 'ERR: '+e.message.slice(0,160)}};
const as=(u:string|null)=>db.exec(`UPDATE auth.cur SET uid=${u?`'${u}'`:'NULL'}`);
const snap=()=>q(`select (select count(*) from general_ledger) gl,(select count(*) from general_ledger where reference_id like 's14b1:%') s14,(select sum(withdrawable_balance) from wallets) w,(select count(*) from agent_collections where reversed_at is null and id in (select collection_id from fin_s14_batch_cases)) unrev,(select sum(amount_repaid) from rent_requests) rr`);
await db.exec(readFileSync(process.env.S14_SEED ?? 'seed.sql','utf8'));
await db.exec(readFileSync('/dev-server/supabase/pending/stage14d_batch1_executor.sql','utf8'));
const log=(n:string,v:any)=>console.log(n.padEnd(46),JSON.stringify(v));
log('T0 applied; fingerprint',await q('select fin_s14b1_fingerprint() f'));
log('T1 validate all_ok',(await q('select fin_s14b1_validate() v') as any)[0].v);
log('T2 snapshot before',await snap());
await as(AGENT); log('T3 non-CFO approve',await q(`select cfo_s14b1_approve(fin_s14b1_fingerprint(),'agent trying it')`));
log('T4 non-CFO execute',await q(`select cfo_s14b1_execute(gen_random_uuid(),true)`));
log('T5 non-CFO manifest',await q(`select cfo_s14b1_manifest()`));
await as(CFO);
log('T6 approve wrong hash',await q(`select cfo_s14b1_approve('abc','CFO approval test')`));
log('T7 approve short reason',await q(`select cfo_s14b1_approve(fin_s14b1_fingerprint(),'ok')`));
const ap=(await q(`select cfo_s14b1_approve(fin_s14b1_fingerprint(),'CFO approves Stage 14 Batch 1 package v1') id`) as any)[0].id;
log('T8 approve OK -> id',ap);
await db.exec(`insert into cfo_approval_approvers values ('${CFO2}')`);
log('T8b same CFO approves and executes',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await as(CFO2);
log('T9 execute approved=false',await q(`select cfo_s14b1_execute('${ap}',false)`));
log('T10 execute approved=NULL',await q(`select cfo_s14b1_execute('${ap}',NULL)`));
log('T11 execute unknown approval',await q(`select cfo_s14b1_execute(gen_random_uuid(),true)`));
log('T12 tamper package row',await q(`update fin_s14b1_package_lines set amount=1 where kind='cash' and case_position=1`));
log('T13 add package row',await q(`insert into fin_s14b1_package_lines select entry_key||'x',kind,case_position,collection_id,rent_request_id,recipient_user_id,origin_group_id,origin_leg_ids,debit_account,credit_account,amount,origin_leg_amount from fin_s14b1_package_lines limit 1`));
// wallet drift -> must abort whole run
await db.exec(`update wallets set withdrawable_balance=withdrawable_balance-1 where user_id='e1bb1b7c-14a6-4a25-a82c-dffe345b7170'`);
log('T14 wallet changed -> execute',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot (unchanged?)',await snap());
await db.exec(`update wallets set withdrawable_balance=withdrawable_balance+1 where user_id='e1bb1b7c-14a6-4a25-a82c-dffe345b7170'`);
await db.exec(`update rent_requests set amount_repaid=amount_repaid+1 where id='1019b84b-b964-4d38-a97e-5d56978499e0'`);
log('T15 plan changed -> execute',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await db.exec(`update rent_requests set amount_repaid=amount_repaid-1 where id='1019b84b-b964-4d38-a97e-5d56978499e0'`);
await db.exec(`update agent_collections set reversed_at=now() where id='7b405673-db1c-421f-85d8-074a5c2dd598'`);
log('T16 collection reversed -> execute',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await db.exec(`update agent_collections set reversed_at=NULL where id='7b405673-db1c-421f-85d8-074a5c2dd598'`);
await db.exec(`insert into general_ledger(amount,direction,category,ledger_scope,reference_id) values (1,'cash_in','x','platform','s14b1:planted')`);
log('T17 foreign s14b1 key -> execute (should still pass: keys exact)',(await q(`select (fin_s14b1_validate()->>'keys_used') k`)));
await db.exec(`delete from general_ledger where reference_id='s14b1:planted'`);
await db.exec(`insert into general_ledger(amount,direction,category,ledger_scope,reference_id) select 1,'cash_in','x','platform',entry_key from fin_s14b1_package_lines limit 1`);
log('T18 one real key used -> execute',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await db.exec(`delete from general_ledger where category='x'`);
// mid-run failure: make one plan update fail after ledger posting -> whole rollback
await db.exec(`create function boom() returns trigger language plpgsql as $$begin if NEW.id='2ca84e52-973b-4ed6-a5b8-5bc28ba6cd84' then raise exception 'injected failure'; end if; return NEW; end$$; create trigger boom before update on rent_requests for each row execute function boom();`);
log('T19 failure injected at last step',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot (no partial?)',await snap());
await db.exec(`drop trigger boom on rent_requests`);
// Referral hard stop: (a) unpaid bonus present before run, (b) bonus paid during run
await db.exec(`insert into referrals(referrer_id,referred_id) values (gen_random_uuid(),'dc5ba4af-cb53-4fe8-9aa5-b1b73d0402aa')`);
log('T19b pending referral before run',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await db.exec(`delete from referrals`);
await db.exec(`create function refpay() returns trigger language plpgsql as $$begin insert into general_ledger(amount,direction,category,ledger_scope,source_table) values (500,'cash_in','referral_bonus','wallet','referrals'); return NEW; end$$; create trigger refpay after update on rent_requests for each row execute function refpay();`);
log('T19c referral paid during run',await q(`select cfo_s14b1_execute('${ap}',true)`)); log('   snapshot',await snap());
await db.exec(`drop trigger refpay on rent_requests`);
const w0=await q(`select left(user_id::text,8) u, withdrawable_balance, float_balance from wallets order by 1`);
log('T20 EXECUTE',await q(`select cfo_s14b1_execute('${ap}',true) r`));
log('   snapshot after',await snap());
log('   wallets before',w0); log('   wallets after',await q(`select left(user_id::text,8) u, withdrawable_balance, float_balance from wallets order by 1`));
log('   totals',await q(`select count(*) legs, count(distinct transaction_group_id) grp, sum(amount) filter (where direction='cash_in') cin, sum(amount) filter (where direction='cash_out') cout from general_ledger where reference_id like 's14b1:%'`));
log('   unbalanced groups',await q(`select count(*) from (select transaction_group_id from general_ledger where reference_id like 's14b1:%' group by 1 having sum(case when direction='cash_in' then amount else -amount end)<>0) x`));
log('   plans',await q(`select left(id::text,8) p,amount_repaid,status,total_repayment-amount_repaid out from rent_requests order by 1`));
log('   recruiter legs',await q(`select count(*) from general_ledger where reference_id like 's14b1:%' and left(user_id::text,8) in ('98ee118b','ebd985fb','ebf0897b')`));
log('   16 Sep set',await q(`select count(*),sum(amount) from agent_collections where reversed_at='2026-09-16 14:08:40.882504+00'`));
log('   29 Sep row',await q(`select reversed_at from agent_collections where id='dab3bc9f-1ba2-4151-a344-fdd09132b7f8'`));
log('   mapped per group',await q(`with m as (select g.transaction_group_id t, g.ledger_scope||'.'||g.category||'/'||g.direction k, case when g.ledger_scope='wallet' then 'L1' else coalesce(am.account_code,'A9') end acct, (g.direction=coalesce(am.debit_when, case when g.ledger_scope='wallet' then 'cash_out' else 'cash_in' end)) dr, g.amount from general_ledger g left join ledger_account_map am on am.ledger_scope=g.ledger_scope and am.category=g.category where g.reference_id like 's14b1:%:commission') select string_agg(distinct acct||case when dr then ' DR' else ' CR' end, ' / ') shape, count(distinct t) groups, sum(amount) filter (where dr) dr, sum(amount) filter (where not dr) cr from m`));
log('   float after (should equal before)',await q(`select sum(float_balance) from wallets`));
log('T21 second execute same approval',await q(`select cfo_s14b1_execute('${ap}',true)`));
await as(CFO);
const ap2=await q(`select cfo_s14b1_approve(fin_s14b1_fingerprint(),'second approval attempt for test')`);
log('T22 new approval after execution',ap2);
log('   event label',await q(`select event_type from system_events`));
log('   s14b1 legs after retries',await snap());
